package frontend;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.Window.Type;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import javax.swing.JCheckBox;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;

public class AddTeacherModal extends JFrame {

	private JPanel contentPane;
	private JTextField nameTextField;
	private JTextField phoneNumField;
	private JTextField addressTextField;
	private JTextField idTextField;
	private JTextField isPartTimeTextField;
	private JTextField moduleTextField;
	private JButton addButton;
	private JLabel autogenerated;
	private JTextField passwordTextField;
	private JLabel hidePassword;

	/**
	 * Launch the application.
	 */
	
	
	
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					AddTeacherModal frame = new AddTeacherModal();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}



	public JLabel getHidePassword() {
		return hidePassword;
	}



	public JTextField getPasswordTextField() {
		return passwordTextField;
	}



	public JLabel getAutogenerated() {
		return autogenerated;
	}



	public JPanel getContentPane() {
		return contentPane;
	}



	public JTextField getNameTextField() {
		return nameTextField;
	}



	public JTextField getPhoneNumField() {
		return phoneNumField;
	}



	public JTextField getAddressTextField() {
		return addressTextField;
	}



	public JTextField getIdTextField() {
		return idTextField;
	}



	public JTextField getIsPartTimeTextField() {
		return isPartTimeTextField;
	}



	public JTextField getModuleTextField() {
		return moduleTextField;
	}



	public JButton getAddButton() {
		return addButton;
	}



	/**
	 * Create the frame.
	 */
	public AddTeacherModal() {
		setResizable(false);
		setType(Type.UTILITY);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 570, 656);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JPanel panel = new JPanel();
		panel.setBackground(new Color(64, 128, 128));
		panel.setBounds(0, 0, 605, 643);
		contentPane.add(panel);
		panel.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("Teacher Name");
		lblNewLabel.setFont(new Font("Century Gothic", Font.BOLD, 20));
		lblNewLabel.setForeground(new Color(255, 255, 255));
		lblNewLabel.setBounds(77, 117, 166, 36);
		panel.add(lblNewLabel);
		
		nameTextField = new JTextField();
		nameTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		nameTextField.setBounds(77, 163, 394, 32);
		panel.add(nameTextField);
		nameTextField.setColumns(10);
		
		JLabel lblNewLabel_1 = new JLabel("Phone Number");
		lblNewLabel_1.setForeground(new Color(255, 255, 255));
		lblNewLabel_1.setFont(new Font("Century Gothic", Font.BOLD, 20));
		lblNewLabel_1.setBounds(77, 205, 156, 36);
		panel.add(lblNewLabel_1);
		
		phoneNumField = new JTextField();
		phoneNumField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		phoneNumField.setBounds(77, 251, 394, 32);
		panel.add(phoneNumField);
		phoneNumField.setColumns(10);
		
		JLabel lblNewLabel_1_1 = new JLabel("Address");
		lblNewLabel_1_1.setForeground(Color.WHITE);
		lblNewLabel_1_1.setFont(new Font("Century Gothic", Font.BOLD, 20));
		lblNewLabel_1_1.setBounds(77, 293, 156, 36);
		panel.add(lblNewLabel_1_1);
		
		addressTextField = new JTextField();
		addressTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		addressTextField.setColumns(10);
		addressTextField.setBounds(77, 339, 394, 32);
		panel.add(addressTextField);
		
		JLabel lblNewLabel_2 = new JLabel("Module to assign");
		lblNewLabel_2.setForeground(new Color(255, 255, 255));
		lblNewLabel_2.setFont(new Font("Century Gothic", Font.BOLD, 15));
		lblNewLabel_2.setBounds(249, 490, 125, 17);
		panel.add(lblNewLabel_2);
		
		addButton = new JButton("Add");
		addButton.setForeground(new Color(255, 255, 255));
		addButton.setFont(new Font("Century Gothic", Font.BOLD, 15));
		addButton.setBackground(new Color(45, 204, 112));
		addButton.setBounds(77, 537, 394, 36);
		panel.add(addButton);
		
		idTextField = new JTextField();
		idTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		idTextField.setColumns(10);
		idTextField.setBounds(77, 76, 394, 32);
		panel.add(idTextField);
		
		JLabel lblTeacherId = new JLabel("Teacher ID");
		lblTeacherId.setForeground(Color.WHITE);
		lblTeacherId.setFont(new Font("Century Gothic", Font.BOLD, 20));
		lblTeacherId.setBounds(77, 30, 166, 36);
		panel.add(lblTeacherId);
		
		isPartTimeTextField = new JTextField();
		isPartTimeTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		isPartTimeTextField.setColumns(10);
		isPartTimeTextField.setBounds(161, 482, 82, 32);
		panel.add(isPartTimeTextField);
		
		moduleTextField = new JTextField();
		moduleTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		moduleTextField.setColumns(10);
		moduleTextField.setBounds(385, 482, 86, 32);
		panel.add(moduleTextField);
		
		autogenerated = new JLabel("Auto Generated");
		autogenerated.setVisible(false);
		autogenerated.setFont(new Font("Century Gothic", Font.BOLD, 20));
		autogenerated.setBounds(78, 75, 165, 32);
		panel.add(autogenerated);
		
		JLabel lblNewLabel_3 = new JLabel("Is Part Time");
		lblNewLabel_3.setForeground(new Color(255, 255, 255));
		lblNewLabel_3.setFont(new Font("Century Gothic", Font.BOLD, 15));
		lblNewLabel_3.setBounds(77, 494, 82, 13);
		panel.add(lblNewLabel_3);
		
		hidePassword = new JLabel("Password");
		hidePassword.setForeground(Color.WHITE);
		hidePassword.setFont(new Font("Century Gothic", Font.BOLD, 20));
		hidePassword.setBounds(77, 381, 156, 36);
		panel.add(hidePassword);
		
		passwordTextField = new JTextField();
		passwordTextField.setFont(new Font("Century Gothic", Font.PLAIN, 15));
		passwordTextField.setColumns(10);
		passwordTextField.setBounds(77, 427, 394, 32);
		panel.add(passwordTextField);
	}
}
